name: Project Automation

on:
  pull_request:
    types: [opened, reopened]
  create:

jobs:
  automate:
    uses: vdelrazo/engineering-standards/.github/workflows/project-automation.yml@main
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
